### ISSUE TITLE
Errors in pinout diagram

### ISSUE THREAD

**Issue by techpaul** [Infineon/Assets#1]
The errors are more about wrong labelling or wrong lines

1/ The lines on bottom of image are in REVERSE order so Description of P0.5 (Arduino 26) is shown by line connecting to P0.13 and vice versa., for the group on right (P0.5, P0.6, P0.10, P0.11, P0.13)
  Likewise for P2.5, P2.7

2/ Reset pin whilst this marked on the board as Reset (Arduino pin 2)no core function takes this as an interrupt to perform a soft reset and is actually a STD input or Analog input. There is no actual RESET pin on the XMC1100

**Comment by techpaul** [comment]
If not obvious this is on  

XMC1100 Boot Kit Pin out diagram

**Comment by mhollfelder** [comment]
Thanks a lot for the feedback here, I will fix this immediately.
I will clarify whether we could implement a SW RESET and trigger this as well to enable the RESET pin.

Best regards,

Manuel Hollfelder

**Comment by techpaul** [comment]
Any software implementation could also do with a way to do sw reset from debugger and on most Arduino platforms change of baud rate on host Serial Monitor triggers a sw reset usfeul for Arduino style debugging

**Comment by mhollfelder** [comment]
I uploaded a new pin out diagram right now.
For the RESET, I will come back once we have discussed this.

Thank you very much again for all your feedback!

Best regards,

Manuel

**Comment by techpaul** [comment]
Board pins 36 to 40 now right.

Board pns 33 and 34 still WRONG

Await decisions on Reset pin which is current SPI SS_2 which can only be used as INPUT for device to act as slave device only. Hence why used for ICSP

**Comment by mhollfelder** [comment]
> Board pins 36 to 40 now right.

I forgot to switch the pin numbering for Arduino, will fix now as well.

> Board pns 33 and 34 still WRONG

Will fix it now. Sorry, oversaw this.

Additionally, there were pin numbers assigned to the power pins below/above RESET, will fix this as well.

I think that we will try to trigger an ISR for a RESET, but we need to check for available resources.
It would make sense to switch this behavior via `#define` to still act for SPI SS for ICSP, but we will discuss it internally.

Best regards,

Manuel

**Comment by techpaul** [comment]
Looking a lot better glad to see updated into wiki for XMC-for-Arduino as well.

Await details on RESET issue

**Comment by techpaul** [comment]
As RESET pin code has been add to V1.1.0 board library this issue is now closed
