### ISSUE TITLE
More error in Pinout Diagram

### ISSUE THREAD

**Issue by techpaul** [Infineon/Assets#2]
XMC1100 Boot Kit Pin out diagram

The power Pins ALL of them have been given Arduino pin numbers these should be REMOVED as they are NOT programmable Arduino pins, duplicate existing Arduino pin numbers wrongly and in one case it is completely wrong.

**Wrong pin**
The pin marked RESET is  NOT a reset pin it is hardwired to P2.4 (board pin 41) and is connected to ICSP header  and has following details as per ICSP header

Signal   Arduino  Port  Board
SPI_SS_2    23     P2.4    41

**Comment by mhollfelder** [comment]
Referencing issue #1  
 
I was fixing the other issue #1 and there I came across the same errors as well.
The issues will be fixed with the other problems as well.

Best regards,

Manuel
